version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: biblioteca-worker
    depends_on:
      - api
    env_file:
      - .env
    volumes:
      - ./data:/app/data
